apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-host-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-host-app
  template:
    metadata:
      labels:
        app: api-host-app
    spec:
      containers:
        - name: api-host-app
          image: 124355645386.dkr.ecr.ca-central-1.amazonaws.com/api-host-app:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: api-config
            - secretRef:
                name: api-secrets
