apiVersion: v1
kind: Service
metadata:
  name: api-host-service
  namespace: default
spec:
  selector:
    app: api-host-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
